name       : wine
version    : '3.3'
release    : 1002
source     :
    - https://dl.winehq.org/wine/source/3.x/wine-3.3.tar.xz : 0594bdb27bb3f9420dd8cbf3cb8c6a66712c155477837d726abd1e4ab50ca333
    - https://github.com/wine-staging/wine-staging/archive/v3.3.tar.gz : e6b3a36b9a148e3af7b961ee45d82a24d5667b4ac161415a8f6e0070b1d8865a
    - https://github.com/sarnex/wine-d3d9-patches/archive/wine-d3d9-3.3.tar.gz : 1f45939c7c184975040f5e01a1439c09fab3b530caa8fa79ec5087e1f46d2a74
license    : LGPL-2.1
component  : virt
summary    : Wine compatibility layer for Windows emulation.
description: |
    Wine (originally an acronym for "Wine Is Not an Emulator") is a compatibility layer capable of running Windows applications on several POSIX-compliant operating systems, such as Linux, Mac OSX, & BSD. Instead of simulating internal Windows logic like a virtual machine or emulator, Wine translates Windows API calls into POSIX calls on-the-fly, eliminating the performance and memory penalties of other methods and allowing you to cleanly integrate Windows applications into your desktop. This is the wine staging build.
builddeps  :
    - pkgconfig(dri2proto)
    - pkgconfig(xproto)
    - pkgconfig32(alsa)
    - pkgconfig32(dbus-1)
    - pkgconfig32(d3d)
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(gl)
    - pkgconfig32(glu)
    - pkgconfig32(gnutls)
    - pkgconfig32(gtk+-2.0)
    - pkgconfig32(gtk+-3.0)
    - pkgconfig32(ice)
    - pkgconfig32(lcms2)
    - pkgconfig32(libdrm)
    - pkgconfig32(libgphoto2)
    - pkgconfig32(libmpg123)
    - pkgconfig32(libpng)
    - pkgconfig32(libpulse)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(libturbojpeg)
    - pkgconfig32(libva)
    - pkgconfig32(libv4l1)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(libxslt)
    - pkgconfig32(ncursesw)
    - pkgconfig32(ocl-icd)
    - pkgconfig32(openal)
    - pkgconfig32(OpenCL)
    - pkgconfig32(x11)
    - pkgconfig32(xcb-dri3)
    - pkgconfig32(xcomposite)
    - pkgconfig32(xcursor)
    - pkgconfig32(xext)
    - pkgconfig32(xi)
    - pkgconfig32(xinerama)
    - pkgconfig32(xrandr)
    - pkgconfig32(xshmfence)
    - pkgconfig32(xxf86vm)
    - pkgconfig32(zlib)
    - cups-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
    - libpcap-32bit-devel
    - libpth-32bit-devel
    - openldap-32bit-devel
    - unixodbc-32bit-devel
patterns   :
    - 32bit :
        - /usr/bin/wine
rundeps    :
    - 32bit :
        - freetype2-32bit
        - harfbuzz-32bit
        - libcap2-32bit
        - libgcrypt-32bit
        - libgnutls-32bit
        - libp11-kit-32bit
        - libpng-32bit
        - libtiff-32bit
        - libtxc_dxtn-32bit
        - ncurses-32bit
setup      : |
    # Apply wine staging patches
    mkdir staging
    tar xf ${sources}/v${version}.tar.gz --strip-components=1 -C staging
    sh ./staging/patches/patchinstall.sh --all DESTDIR=`pwd`

    # D3D9 support (gallium nine patches)
    mkdir d3d9
    tar xf ${sources}/wine-d3d9-${version}.tar.gz --strip-components=1 -C d3d9
    %patch -p1 < ./d3d9/staging-helper.patch
    %patch -p1 < ./d3d9/wine-d3d9.patch

    autoreconf -vfi

    # Get 64-bit done first.
    mkdir wine64 && pushd wine64
    ../configure %CONFOPTS% \
        --enable-win64 \
        --with-x
    popd

    # 32-bit now
    mkdir wine32 && pushd wine32
    PKG_CONFIG_PATH=/usr/lib32/pkgconfig:/usr/share/pkgconfig:/usr/lib64/pkgconfig ../configure %CONFOPTS% \
        --with-wine64=../wine64 \
        --libdir=/usr/lib32 \
        --with-x
    popd
build      : |
    %make -C wine64
    %make -C wine32
install    : |
    %make_install -C wine32
    %make_install -C wine64

    # Note: systemd-binfmt must be (re)started for this to work
    install -Dm00644 $pkgfiles/wine.binfmt $installdir/%libdir%/binfmt.d/wine.conf

    # Font aliasing settings for Win32 applications
    install -dm00755 $installdir/usr/share/fonts/conf.d
    install -Dm00644 $pkgfiles/30-win32-aliases.conf -t $installdir/usr/share/fontconfig/conf.avail
    ln -s /usr/share/fontconfig/conf.avail/30-win32-aliases.conf $installdir/usr/share/fonts/conf.d/30-win32-aliases.conf
